# Generated by Django 3.2.9 on 2022-05-16 09:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetdata',
            name='income',
        ),
        migrations.CreateModel(
            name='IncomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('income', models.FloatField(default=0)),
                ('user_income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetdata')),
            ],
        ),
    ]
