# Generated by Django 3.2.9 on 2021-12-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdata',
            name='income',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetdata',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
