# Generated by Django 3.2.9 on 2022-01-13 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0002_auto_20211201_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetdata',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='budgetdata',
            name='income',
        ),
        migrations.RemoveField(
            model_name='budgetdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='budgetdata',
            name='user_budget',
        ),
        migrations.AddField(
            model_name='budgetdata',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='budgetdata',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='budgetdata',
            name='user_expense',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
