# Generated by Django 3.2.9 on 2022-05-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20220113_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdata',
            name='income',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='budgetdata',
            name='category',
            field=models.TextField(choices=[('Spożywcze', 'Spożywcze'), ('Chemia', 'Chemia'), ('Rachunki', 'Rachunki'), ('Alkohol', 'Alkohol'), ('Gry', 'Gry')], default='Spożywcze'),
        ),
    ]
