# Generated by Django 3.2.9 on 2022-05-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_incomedata_user_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetdata',
            name='cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='income',
            field=models.FloatField(default=0, null=True),
        ),
    ]
